package com.app.common.enums;

public enum ErrorCode {
    VALIDATION_ERROR,
    USER_NOT_FOUND,
    AUCTION_NOT_FOUND,
    NOTIFICATION_NOT_FOUND,
    
    USERNAME_ALREADY_EXISTS,
    PHONE_ALREADY_EXISTS,
    AUCTION_NO_FOLLOWERS,

    INVALID_BID,
    AUCTION_CLOSED,
    BID_CONFLICT,
    AUTOBID_CLOSED,
    AUTOBID_ALREADY_EXISTS,
    AUTOBID_NOT_FOUND,

    EMAIL_ALREADY_EXISTS,
    INCORRECT_PASSWORD,
    OLD_PASSWORD_INCORRECT,
    PASSWORD_NOT_MATCHES,
    USER_NOT_HAVE_NOTIFICATION,

    INSUFFICIENT_BALANCE,
    ACCOUNT_LOCKED,
    ACCOUNT_BANNED,
    INVALID_ITEM_TYPE
}
