package com.app.common.enums;

public enum ErrorCode {
    VALIDATION_ERROR,
    USER_NOT_FOUND,
    AUCTION_NOT_FOUND,
    USERNAME_ALREADY_EXISTS,

    INVALID_BID,
    AUCTION_CLOSED,
    BID_CONFLICT,

    LOGIN_ERROR,
    ACCESS_DENIED,
    EMAIL_ALREADY_EXISTS,
    INCORRECT_PASSWORD,

    INSUFFICIENT_BALANCE,
    ACCOUNT_LOCKED
}
