package com.app.common.enums;

public enum ErrorCode {
    VALIDATION_ERROR,
    USER_NOT_FOUND,
    AUCTION_NOT_FOUND,
    NOTIFICATION_NOT_FOUND,
    
    USERNAME_ALREADY_EXISTS,
    PHONE_ALREADY_EXISTS,

    INVALID_BID,
    AUCTION_CLOSED,
    BID_CONFLICT,
    AUCTION_ALREADY_PAID,

    EMAIL_ALREADY_EXISTS,
    INCORRECT_PASSWORD,
    OLD_PASSWORD_INCORRECT,
    PASSWORD_NOT_MATCHES,

    INSUFFICIENT_BALANCE,
    ACCOUNT_LOCKED
}
