POST http://localhost:8080/users/become-seller
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyNyIsInVzZXJJZCI6InVzZXI3Iiwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9TRUxMRVIiXSwiaWF0IjoxNzc4MjAyOTkyLCJleHAiOjE3NzgyODkzOTJ9.kTNfI56kLl-mrRKLNj0Qfh4SiObo6p_IEWDFDMqZ8o0