POST http://localhost:8080/auth/become-seller
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVU1ItNGIxOGI0NGEiLCJ1c2VySWQiOiJVU1ItNGIxOGI0NGEiLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNzc5MzE3MjA3LCJleHAiOjE3Nzk0MDM2MDd9.Ko50TQwkj40BNzs9MmQ6VKDeKPN2lBpARvw1mtwK68s