POST http://localhost:8080/users/become-seller
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyNyIsInVzZXJJZCI6InVzZXI3Iiwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9TRUxMRVIiXSwiaWF0IjoxNzc4MjA0MDMyLCJleHAiOjE3NzgyOTA0MzJ9.mqvP5lOgbhr8uuxxt1C1ee-XURtL-lUbCmVLcXXrQ6Q