POST http://localhost:8080/bids
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVU1ItMmNmYTkxYzgiLCJ1c2VySWQiOiJVU1ItMmNmYTkxYzgiLCJyb2xlcyI6WyJST0xFX1VTRVIiLCJST0xFX1NFTExFUiJdLCJpYXQiOjE3NzkwNTUyNTYsImV4cCI6MTc3OTE0MTY1Nn0.kWbKTHkc_kQbMrd31hZsi-ErqrWtiELtJuzXHP4On2o
Content-Type: application/json

{
    "auctionId": "AUC-e55cd6c7-",
    "amount": 750
}