POST http://localhost:8080/autobids
Authorization: Bearer 
Content-Type: application/json

{
    "auctionId": "",
    "maxAmount": "2000"
}

GET http://localhost:8080/autobids/me
Authorization: Bearer 


DELETE http://localhost:8080/autobids/