POST http://localhost:8080/auctions
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVU1ItNGIxOGI0NGEiLCJ1c2VySWQiOiJVU1ItNGIxOGI0NGEiLCJyb2xlcyI6WyJST0xFX1VTRVIiLCJST0xFX1NFTExFUiJdLCJpYXQiOjE3NzkzMTcyMjQsImV4cCI6MTc3OTQwMzYyNH0.-BbQVK61yiUawaBZjWshCC50pkoULgWWTc9fUlaUtlg
Content-Type: application/json

{
  "title": "IPhone 15",
  "itemName": "Iphone 15 promax",
  "description": "new, 256GB",
  "startPrice": 450
}
