POST http://localhost:8080/auctions
Authorization: Bearer eyJhbGc...
Content-Type: application/json

{
  "title": "IPhone 15 Auction",

  "itemType": "ELECTRONICS",

  "itemName": "IPhone 15 Pro Max",
  "description": "New 256GB",
  "startPrice": 450,

  "brand": "Apple",
  "model": "15 Pro Max",
  "color": "red",
  "storage": "256GB",
  "conditionStatus": "new",
  "warrantyMonths": "6"
}
